GET https://young-thicket-23579.herokuapp.com/api/persons

###

GET https://young-thicket-23579.herokuapp.com/api/persons/2

###

GET http://localhost:3001/info

###

DELETE https://young-thicket-23579.herokuapp.com/api/persons/5

###

POST  http://localhost:3001/api/persons
content-type: application/json

{
    "name" : "Cassandra",
    "number": "123456"
}