GET https://young-thicket-23579.herokuapp.com/api/persons

###

GET http://localhost:3001/api/persons

###


GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/60c44ac51be1be98e9bcd1a4

###

DELETE http://localhost:3001/api/persons/60cf179e194b43e

###

POST  http://localhost:3001/api/persons
content-type: application/json

{
    "name" : "Jan",
    "number": "5"
}